# Robot-specific calibration parameters
joint_calibration_node:
  ros__parameters:
    joints:
      joint_1:
        offset: 2.90
        direction: 1
        reduction: 6.0
      joint_2:
        offset:  1.38 
        direction: -1
        reduction: 3.0
      joint_3:
        offset: 3.41   
        direction: 1
        reduction: 3.0
      joint_4:
        offset: 3.41   
        direction: 0
        reduction: 1.0
      joint_6:
        offset: 3.41   
        direction: 0
        reduction: 1.0

