CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2C_STM32=y

CONFIG_SENSOR=y
CONFIG_AMS_AS5600=y

CONFIG_MICROROS=y
CONFIG_CPP=y

CONFIG_MAIN_STACK_SIZE=25000
CONFIG_MAIN_THREAD_PRIORITY=3

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=n

CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

CONFIG_POSIX_API=y
CONFIG_POSIX_TIMERS=y
CONFIG_POSIX_CLOCK_SELECTION=y
CONFIG_POSIX_MONOTONIC_CLOCK=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

CONFIG_HEAP_MEM_POOL_SIZE=16384

# USB CDC ACM configuration
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="STM32 CDC"
CONFIG_USB_DEVICE_VID=0x0483
CONFIG_USB_DEVICE_PID=0x5740
CONFIG_USB_CDC_ACM=y
CONFIG_USB_CDC_ACM_RINGBUF_SIZE=256

# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_MICROROS_TRANSPORT_SERIAL_USB=y
